version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'password'
      POSTGRES_USER: 'postgres'
    ports:
      - 5432:5432
  redis:
    image: redis
    command: --save ''
    ports:
      - 6379:6379
